anchor_version = "0.13.2"

[workspace]
members = ["program"]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
token_vesting = "8soLn4k6bqnj6AUAjQu2eWmqynG4zFtyXCQZ1WJRhRuE"
